### ISSUE TITLE
[blueprint] pull requests policies management API

### ISSUE THREAD

**Issue by nilleb** [jasminsehic/infinity.net#16]
Hi Edward,

It would be great if this library could support the management of pull request policies. They have been introduced in TFS 2015, and they help the administrators to define review policies, default reviewers by file path, and so on (I bet you already know this ;-) -- other guys: have a look at this video https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-2015-Final-Release-Event/Git-Branches-and-Policies-in-Team-Foundation-Server-2015).

I could propose a pull request, if only there was a public and documented API.... :-)

**Comment by nilleb** [comment]
I have found a documentation page about git branch policies REST API!
https://www.visualstudio.com/en-us/integrate/api/policy/overview

Along with a more general purpose documentation page
https://msdn.microsoft.com/Library/vs/alm/Code/git/branch-policies

But as of now, it is only possible to *get* a list of the available policies, and not to set them.... :-(

**Comment by ethomson** [comment]
Yeah, I think that the code policy API is still in flux and so they haven't released the specifications for that yet.  You might be able to use fiddler or netmon/wireshark to capture the REST calls from a browser, but I suspect that this is a bit of a moving target.

I'll ask around and see if I can find anything elucidating.

**Comment by ethomson** [comment]
Sorry!  I read this before coffee.  Yes, that should be the documentation for the policy API!

**Comment by jasminsehic** [comment]
@nilleb let me know if you need any help with adding support for this.

**Comment by nilleb** [comment]
@jasminsehic sorry, I have abandoned the effort long time ago (TFS not being anymore part of the tools I use, sorry)
